version: "3.8"

services:
  nginx:
    build:
      context: nginx
      dockerfile: dev.Dockerfile
    ports:
      - '3000:3000'

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - "mongo-data:/data/db"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: intelsy
      MONGO_INITDB_DATABASE: game

volumes:
  mongo-data:
